version: '3.8'

services:
  syslog-ng-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "514:514/udp"  # Expose FortiGate UDP port
      - "515:515/udp"  # Expose Palo Alto UDP port
    volumes:
      - ./syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf  # Mount the configuration directory
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: "4G"
        reservations:
          cpus: "0.25"
          memory: "256M"
    restart: always
